name: Python test

on:
    push:
        branches: [main]
        paths:
          - app/** 
    

jobs:
    linter-test:
        runs-on: ubuntu-latest


        steps:
            - name: checkout Python 3.11.6
              uses: actions/checkout@v2

            - name: Set Up Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11.6'
                cache: 'pip'

            - name: Install Dependencies
              run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt

            - name: Tests
              run: |
               python test_task.py

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Build and Push Docker image
              env:
                REPOSITORY: pythontest
                IMAGE_TAG: latest
              run: |
                docker build -t ${{secrets.DOCKERHUB_USERNAME}}/$REPOSITORY:$IMAGE_TAG .
                docker push ${{secrets.DOCKERHUB_USERNAME}}/$REPOSITORY:$IMAGE_TAG

